### ISSUE TITLE
KeyError: 'multi_scale_loss' on training the backbone

### ISSUE THREAD

**Issue by hachreak** [wgcban/HyperTransformer#13]
Hi @wgcban ,
thank you very much to publish the code for the paper!

I was trying to train the backbone (first stage):

```bash
python train.py --config configs/config_HSIT_PRE.json
```

But, the training script is raising an error: 

```python
Traceback (most recent call last):
  File "train.py", line 346, in <module>
    train(epoch)
  File "train.py", line 198, in train
    if config[config["train_dataset"]]["multi_scale_loss"]:
KeyError: 'multi_scale_loss'
```

Is the configuration value for `multi_scale_loss` missing?
Which value do I need to set?
Thanks for your help! :D

**Comment by YusenZheng** [comment]
Have you ever solved this problem?

**Comment by jorel666** [comment]
Hi @wgcban! Hey @wgcban, your AI/ML Developer work caught my eye.

ARKHAN is a fractal AI system with 59 specialized chips: autonomous scraping, crypto monitoring, content generation, income automation. API access $29/mo.

Store: https://fractalaixipetotec.online
Card payment: https://xipetotec.lemonsqueezy.com/checkout/buy/d5943e3e-b661-4011-a995-826847b87156

Reply STOP to opt out.

Pago directo USDT TRC20: TWJv7sD1nTWeHFsaMDBuJEEAc62VoxPmvm
Ref: pay_68e2d35a123e

*Automated outreach — reply NO to stop.*
